{
 "title": "flask-app",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Flask app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS (queries per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_app_http_requests_total[1m]))\n",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Errors (4xx, 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_app_http_requests_total{status=~\"4..\"}[1m]))\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(flask_app_http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_app_http_requests_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95 latency"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_app_http_requests_total[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}